#!/usr/bin/env bash
# rhel9-app-install.sh — MANUAL/DEBUGGING FALLBACK ONLY.
#
# The real deployment path is push-based: a separate deploy script, run
# from a dev machine or CI, pushes code onto the server and triggers this
# same install-and-migrate logic remotely over SSH. Nobody logs into the
# server and runs this by hand as the normal way to deploy.
#
# This script exists so that if a real deploy fails partway, you can log
# into the server and re-run these exact steps by hand to see precisely
# where it broke. It installs this project's Python dependencies and runs
# database migrations, WITHOUT uv — requirements.txt is committed to git by
# developers (see infra/scripts/generate-requirements.sh) and arrives with
# the rest of the code; this script never installs or calls uv itself.
#
# Run this directly on the RHEL9 box, in the app's own directory
# (e.g. /opt/risk-workbench), AFTER the code has already been synced there.
#
# Usage: PYTHON_BIN=python3.14 ./rhel9-app-install.sh
#   (run from inside the app directory, e.g. /opt/risk-workbench)

set -euo pipefail

PYTHON_BIN="${PYTHON_BIN:-python3.14}"

# Check that the actual application code is here before doing anything
# else — this script does NOT fetch or sync code itself, that's a separate
# step (the deploy script, or git/rsync run by hand). Checking explicitly,
# up front, means a missing checkout fails immediately with a clear
# message, instead of failing confusingly deep into a later step (e.g.
# "alembic upgrade head" erroring because alembic/ doesn't exist).
for required in app pyproject.toml alembic requirements.txt; do
    if [ ! -e "$required" ]; then
        echo "ERROR: '$required' not found in $(pwd)." >&2
        echo "       This script does not fetch code — sync/clone the repo" >&2
        echo "       into this directory first, then re-run." >&2
        exit 1
    fi
done

if [ ! -f infra/.env ]; then
    echo "ERROR: infra/.env not found." >&2
    echo "       This file holds real secrets and is never generated by any" >&2
    echo "       script — place it here manually before running this." >&2
    exit 1
fi

echo "=== 1. Virtual environment ==="
# A "virtual environment" is a private, self-contained folder holding its
# own copy of Python and installed packages — separate from RHEL9's system
# Python, so this project's exact dependency versions can't clash with
# anything else on the box. "-d" checks "does .venv already exist as a
# folder?" — only create it if it doesn't, so re-running this script
# doesn't wipe out and rebuild an already-working environment for no
# reason.
if [ ! -d .venv ]; then
    "$PYTHON_BIN" -m venv .venv
    echo "  Created .venv"
else
    echo "  .venv already exists"
fi

# "source .venv/bin/activate" changes the CURRENT SHELL so that typing
# "python" or "pip" from here on uses the virtual environment's private
# copies, not RHEL9's system-wide ones. This only affects this one running
# script/terminal session — it doesn't change anything system-wide or
# permanently.
source .venv/bin/activate

echo ""
echo "=== 2. Install dependencies (hash-verified, no uv) ==="
# requirements.txt's first line is "-e ." — a reference to this project's
# own code, meaning "also install this, as a live editable link back to
# its source folder." pip's strict hash-checking mode (--require-hashes,
# below) refuses this outright: a local directory reference has no
# downloadable file to compute a hash against, editable or not. This is
# NOT fixable by asking uv to export it differently — `uv export
# --no-editable` was tried and confirmed to still produce an unhashed
# local-path line (just "." instead of "-e .") for the exact same
# structural reason, so generate-requirements.sh intentionally does NOT
# use --no-editable; stripping this one line at install time, here, is the
# actual fix, not a workaround to later replace.
# "grep -v" means "print every line EXCEPT ones matching this pattern" — so
# this builds a temporary copy of the file with that one line removed.
grep -v '^-e \.' requirements.txt > /tmp/requirements-deps.txt

# --require-hashes makes pip check every single package's actual downloaded
# content against the exact hash uv recorded when the lock file was built —
# it refuses to install anything that doesn't match exactly. This is the
# real integrity guarantee: nobody can quietly swap in a different package
# version without this failing loudly.
#
# --extra-index-url adds a second place pip is allowed to look for packages,
# in addition to the normal public PyPI. This project's irp-integration
# dependency currently needs this — its pinned version lives on TestPyPI
# (a pre-release testing index), not the main PyPI. See AGENTS.md's
# irp-integration section; this is flagged there as something to revisit.
pip install --require-hashes --extra-index-url https://test.pypi.org/simple/ \
    -r /tmp/requirements-deps.txt

# Now install the project's own code, separately, as a normal (not
# editable) package — --no-deps means "don't try to re-figure-out and
# install its dependencies again," since the line above already did that
# exactly, with hashes verified. Re-resolving here could pull in different,
# unpinned versions by accident.
pip install --no-deps .

echo ""
echo "=== 3. Verify pyodbc compiled correctly ==="
# pyodbc has a C extension (compiled code, not plain Python) that has to be
# built against this specific machine's ODBC headers. This check confirms
# that actually worked, and that it can see the SQL Server driver installed
# earlier in rhel9-setup.sh.
"$PYTHON_BIN" -c "import pyodbc; print('pyodbc OK, drivers:', pyodbc.drivers())"

echo ""
echo "=== 4. Database migrations ==="
# "set -a" makes every variable this shell sets from now on automatically
# available to programs it runs (normally a shell variable is private to
# itself). "source infra/.env" reads that file and sets each line in it as
# a variable. "set +a" turns the auto-sharing back off afterward. This is
# how the database password and other settings in infra/.env actually reach
# the Python programs below — they read these as environment variables, not
# by opening the file themselves.
set -a
source infra/.env
set +a

"$PYTHON_BIN" infra/scripts/bootstrap_db.py
alembic upgrade head

echo ""
echo "=== Verify app config loads ==="
"$PYTHON_BIN" -c "import app.config; print('app imports OK')"

echo ""
echo "=== Done. ==="
echo "Dependencies installed, migrations applied. Next: start the app"
echo "(uvicorn, Valkey, nginx) — see docs/RHEL9/RHEL9_DEPLOYMENT.md steps 5-7,"
echo "or infra/scripts/rhel9/rhel9-start.sh / rhel9-stop.sh."
